[package]
name = "lab2-tfl"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
rand = "0.8.3"
image = "0.24"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.7.1"
